### ISSUE TITLE
neutron_* things should be merged to ansible-modules-core

### ISSUE THREAD

**Issue by toddnni** [openstack-ansible/openstack-ansible-modules#29]
Hi,

I think we should merge neutron_* things to ansible-modules/core/cloud/openstack (https://github.com/ansible/ansible-modules-core/tree/devel/cloud/openstack)

It is confusing for newcomers that similar modules are split in two places. I can try to make one crude merge, but I don't know how this project or ansible project will react.

**Comment by lorin** [comment]
See discussion on #40.

**Comment by lorin** [comment]
:smile:
